/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2025-10-29 08:32:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.movie;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class movie_005fpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/include/footer.jsp", Long.valueOf(1761711747085L));
    _jspx_dependants.put("/WEB-INF/views/include/header.jsp", Long.valueOf(1761721124461L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>영화 카드</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".movie-grid {\r\n");
      out.write("	display: grid;\r\n");
      out.write("	grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));\r\n");
      out.write("	gap: 20px;\r\n");
      out.write("	max-width: 800px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".movie-card {\r\n");
      out.write("	background: white;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	box-shadow: 0 2px 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	transition: transform 0.2s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".movie-card:hover {\r\n");
      out.write("	transform: translateY(-5px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".poster {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 280px;\r\n");
      out.write("	object-fit: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".movie-info {\r\n");
      out.write("	padding: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".movie-title {\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	margin-bottom: 6px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".movie-meta {\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("	color: #777;\r\n");
      out.write("}\r\n");
      out.write(".prod-box-1 {\r\n");
      out.write("	width : 1100px;\r\n");
      out.write("	height : 800px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Header CSS -->\r\n");
      out.write("<style>\r\n");
      out.write("/* 폰트 적용 */\r\n");
      out.write("@import url(//fonts.googleapis.com/earlyaccess/notosanskr.css);\r\n");
      out.write("html {\r\n");
      out.write("    font-family: \"notokrR\", sans-serif, \"Noto Sans KR\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 공통 라이브러리 CSS */\r\n");
      out.write(".con {\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    width: 980px;\r\n");
      out.write("}\r\n");
      out.write(".row::after {\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    display: block;\r\n");
      out.write("    clear: both;\r\n");
      out.write("}\r\n");
      out.write(".cell {\r\n");
      out.write("    float: left;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write(".cell-right {\r\n");
      out.write("    float: right;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write(".cell-left img{\r\n");
      out.write("	width:100%;\r\n");
      out.write("	height:100%;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".cell-left {\r\n");
      out.write("	width:50px;\r\n");
      out.write("	height:50px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".block {\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write(".inline-block {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("}\r\n");
      out.write(".text-align-center {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".line-height-0-ch-only {\r\n");
      out.write("    line-height: 0;\r\n");
      out.write("}\r\n");
      out.write(".line-height-0-ch-only > * {\r\n");
      out.write("    line-height: normal;\r\n");
      out.write("}\r\n");
      out.write(".relative {\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write(".absolute-left {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    left: 0;\r\n");
      out.write("}\r\n");
      out.write(".absolute-right {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    right: 0;\r\n");
      out.write("}\r\n");
      out.write(".absolute-middle {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    transform: translateY(-50%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 노말라이즈 */\r\n");
      out.write("body, ul, li, h1 {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    list-style: none;\r\n");
      out.write("}\r\n");
      out.write("a {\r\n");
      out.write("    color: inherit;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("body {\r\n");
      out.write("    padding-top: 80px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Header 스타일 */\r\n");
      out.write(".ttop {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    z-index: 2;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 194px;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    border-bottom: none;\r\n");
      out.write("    background-color: transparent;\r\n");
      out.write("    background: -moz-linear-gradient(top, rgba(29,29,31,1) 0%, rgba(0,0,0,0) 100%);\r\n");
      out.write("    background: -webkit-linear-gradient(top, rgba(29,29,31,1) 0%, rgba(0,0,0,0) 100%);\r\n");
      out.write("    background: linear-gradient(to bottom, rgba(29,29,31,1) 0%, rgba(0,0,0,0) 100%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-bar {\r\n");
      out.write("    margin-top: -80px;\r\n");
      out.write("    z-index: 10;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-bar .menu-1 > ul > li > a {\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    height: 14px;\r\n");
      out.write("    color: #afafaf;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-bar .menu-1 > ul > li > a > img {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding: 0 10px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    height: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-bar .menu-1 > ul > li:hover > a {\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-bar .search-box > ul > li {\r\n");
      out.write("    padding-left: 8px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    color: darkgray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top-bar {\r\n");
      out.write("    border-top: 2px solid rgba(255, 255, 255, .3);\r\n");
      out.write("    border-bottom: 2px solid #fff;\r\n");
      out.write("    border-bottom-color: rgba(255, 255, 255, .3);\r\n");
      out.write("    color: white;\r\n");
      out.write("    top: 20px;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    z-index: 10;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top-bar .menu-box-1 ul > li > a {\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top-bar .menu-box-1 > ul > li > a {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    padding: 10px 40px;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top-bar .menu-box-1 > ul > li > a::after {\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    bottom: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 3px;\r\n");
      out.write("    background-color: #FF1744;\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top-bar .menu-box-1 > ul > li:hover > a::after {\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top-bar .menu-2 > div > ul > li > a {\r\n");
      out.write("    padding-left: 0;\r\n");
      out.write("    margin: 10px;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    color: darkgray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top-bar .menu-2 > div > ul > li > a:hover {\r\n");
      out.write("    color: #FFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top-bar .logo {\r\n");
      out.write("    width: 70px;\r\n");
      out.write("    margin-left: 370px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top-bar .menu-box-2 {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin-right: 346px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top-bar .menu-box-2 > ul > li > a {\r\n");
      out.write("    font-size: 11px;\r\n");
      out.write("    padding: 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top-bar > .menu-box-1 > ul > li:hover > div > div {\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top-bar > .menu-box-1 > ul > li > div > div {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    background-color: rgba(0, 0, 0, .7);\r\n");
      out.write("    left: 0;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    margin-bottom: 7px;\r\n");
      out.write("    height: 38px;\r\n");
      out.write("    display: none;\r\n");
      out.write("    z-index: 6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".con-min-width {\r\n");
      out.write("    min-width: 1920px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top-bar .logo img {\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#logo-img {\r\n");
      out.write("width: 100px;\r\n");
      out.write("height: 100px;\r\n");
      out.write("}\r\n");
      out.write(".logo inline-block{\r\n");
      out.write("width:}\r\n");
      out.write("\r\n");
      out.write("#content_1{\r\n");
      out.write("margin-top:20px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Header HTML -->\r\n");
      out.write("<div class=\"ttop\"></div>\r\n");
      out.write("<div class=\"menu-bar relative con text-align-center line-height-0-ch-only\">\r\n");
      out.write("    <nav class=\"menu-1 absolute-left absolute-middle\">\r\n");
      out.write("        <ul class=\"row\">\r\n");
      out.write("            <li class=\"cell cell-left\" ><img src=\"https://i.namu.wiki/i/EYm29AFq9eP2QqG9c7ns7UMD85CFFJeagte2DGY7rZlEsedVGGAt3b_WmEcs7GXEpf8E7yNGDvfq8Ou9-8cN8w.webp\" alt=\"\" width=\"50%\" height=\"50%\" ></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <a class=\"logo inline-block\" href=\"#\" ><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/mainImage/main-logo4.png\" alt=\"로고 사진\" class=\"block\" id=\"logo-img\" ></a>\r\n");
      out.write("    <form class=\"search-box absolute-right absolute-middle\">\r\n");
      out.write("        <ul class=\"row\">\r\n");
      out.write("        \r\n");
      out.write("            <li class=\"cell\"><a href=\"#\">내정보</a></li>\r\n");
      out.write("            <li class=\"cell\"><a href=\"#\">로그아웃</a></li>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <li class=\"cell\"><a href=\"#\">회원가입</a></li>\r\n");
      out.write("            <li class=\"cell\"><a href=\"#\">로그인</a></li>\r\n");
      out.write("            \r\n");
      out.write("        </ul>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"top-bar relative con-min-width\">\r\n");
      out.write("    <nav class=\"menu-box-1 text-align-center line-height-0-ch-only con\">\r\n");
      out.write("        <ul class=\"row inline-block\">\r\n");
      out.write("            <li class=\"cell\">\r\n");
      out.write("                <a href=\"#\" class=\"block\">영화</a>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"menu-2 text-align-center line-height-0-ch-only\">\r\n");
      out.write("                        <div class=\"inline-block\">\r\n");
      out.write("                            <ul class=\"row\">\r\n");
      out.write("                                <li class=\"cell\"><a href=\"/spring/movie\">상영중인 영화</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"cell\">\r\n");
      out.write("                <a href=\"#\" class=\"block\">예매</a>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"menu-2 text-align-center line-height-0-ch-only\">\r\n");
      out.write("                        <div class=\"inline-block\">\r\n");
      out.write("                            <ul class=\"row\">\r\n");
      out.write("                                <li class=\"cell\"><a href=\"#\">빠른예매</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("          \r\n");
      out.write("            <li class=\"cell\">\r\n");
      out.write("                <a href=\"#\" class=\"block\">공지사항& 이벤트 </a>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"menu-2 text-align-center line-height-0-ch-only\">\r\n");
      out.write("                        <div class=\"inline-block\">\r\n");
      out.write("                            <ul class=\"row\">\r\n");
      out.write("                                <li class=\"cell\"><a href=\"#\">이벤트</a></li>\r\n");
      out.write("                                <li class=\"cell\"><a href=\"#\">공지사항</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"prod-box-1\">\r\n");
      out.write("		<div class=\"movie-grid\">\r\n");
      out.write("			<div class=\"movie-card\">\r\n");
      out.write("				<img src=\"https://via.placeholder.com/200x280\" alt=\"범죄도시4\"\r\n");
      out.write("					class=\"poster\">\r\n");
      out.write("				<div class=\"movie-info\">\r\n");
      out.write("					<div class=\"movie-title\">범죄도시4</div>\r\n");
      out.write("					<div class=\"movie-meta\">2024 · 액션 · 15세</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"movie-card\">\r\n");
      out.write("				<img src=\"https://via.placeholder.com/200x280\" alt=\"파묘\"\r\n");
      out.write("					class=\"poster\">\r\n");
      out.write("				<div class=\"movie-info\">\r\n");
      out.write("					<div class=\"movie-title\">파묘</div>\r\n");
      out.write("					<div class=\"movie-meta\">2024 · 미스터리 · 15세</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Footer CSS -->\r\n");
      out.write("<style>\r\n");
      out.write("/* 하단 정렬 */\r\n");
      out.write(".boo {\r\n");
      out.write("    margin-top: 20%;\r\n");
      out.write("    height: 62px;\r\n");
      out.write("    border-top: 1px solid #444444;\r\n");
      out.write("    border-bottom: 1px solid #444444;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".boo > .dff {\r\n");
      out.write("    margin-top: 17px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".boo > .dff > div > .ghj {\r\n");
      out.write("    color: #01738B;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".boo > .dff > .df {\r\n");
      out.write("    color: #666666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 아이콘 교체 리스트 */\r\n");
      out.write(".box-2 {\r\n");
      out.write("    width: 980px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-2 > .menu-box-2 {\r\n");
      out.write("    padding-top: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-2 > .menu-box-2 > ul > li {\r\n");
      out.write("    width: calc(100% / 6);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-2 > .menu-box-2 > ul > li > a {\r\n");
      out.write("    height: 120px;\r\n");
      out.write("    padding-top: 15px;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-2 > .menu-box-2 > ul > li > a > img {\r\n");
      out.write("    display: block;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-2 > .menu-box-2 > ul > li > a > span {\r\n");
      out.write("    display: block;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-2 > .menu-box-2 > ul > li > a > span:hover {\r\n");
      out.write("    text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 광고 영역 */\r\n");
      out.write(".ee {\r\n");
      out.write("    margin-top: 90px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ee > .gee {\r\n");
      out.write("    background: #F8D5DB;\r\n");
      out.write("    padding-top: 0;\r\n");
      out.write("    border-bottom: 1px solid #666666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ee > .gee > .dd {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ee > .gee > .dd img {\r\n");
      out.write("    max-width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 하단 영역 */\r\n");
      out.write(".fdf {\r\n");
      out.write("    border-bottom: 1px solid #666666;\r\n");
      out.write("    margin-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".policy {\r\n");
      out.write("    margin-top: 30px;\r\n");
      out.write("    margin-bottom: 30px;\r\n");
      out.write("    width: 980px;\r\n");
      out.write("    margin-left: auto;\r\n");
      out.write("    margin-right: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".policy > ul > li {\r\n");
      out.write("    font-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".policy > ul > li > .empha-red {\r\n");
      out.write("    color: #E7612E;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".address {\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    width: 980px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".address > .hadan-logo {\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    margin-top: 30px;\r\n");
      out.write("    background-repeat: no-repeat;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".address > .hadan-logo img {\r\n");
      out.write("    max-width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".address > p {\r\n");
      out.write("    margin-left: 40px;\r\n");
      out.write("    margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".address > .cc {\r\n");
      out.write("    margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".address > .cd {\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("    margin-left: 80px;\r\n");
      out.write("}\r\n");
      out.write(".\r\n");
      out.write(".address > .cc > a {\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    float: right;\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 106px;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    line-height: 28px;\r\n");
      out.write("    color: #666;\r\n");
      out.write("    font-size: 13px;\r\n");
      out.write("    border: 1px solid #d8d9db;\r\n");
      out.write("    border-radius: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".address > .cd a {\r\n");
      out.write("    margin-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".address > .cd img {\r\n");
      out.write("    width: 30px;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".qqq {\r\n");
      out.write("    margin-top: 190px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 200px;\r\n");
      out.write("    background: black;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer HTML -->\r\n");
      out.write("<div class=\"boo\">\r\n");
      out.write("    <div class=\"con dff\">\r\n");
      out.write("        <div class=\"cell\">\r\n");
      out.write("            <a href=\"#\">지점 ｜</a>\r\n");
      out.write("            <a href=\"#\" class=\"ghj\"> [종각역 점]</a>\r\n");
      out.write("            <a href=\"#\">12/20~21 운영시간 조정 안내</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"cell-right df\">\r\n");
      out.write("            <a href=\"#\">2025.11.09 ｜ </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"ee\">\r\n");
      out.write("    <div class=\"gee\">\r\n");
      out.write("        <div class=\"dd text-align-center\">\r\n");
      out.write("            <img src=\"http://adimg.cgv.co.kr/images/201709/house/0929_980X240.png\" alt=\"광고-CGV 기프트 카드\" border=\"0\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"address con\">\r\n");
      out.write("    <div class=\"hadan-logo cell\">\r\n");
      out.write("        <img src=\"https://waifu2x.booru.pics/outfiles/a98fa46dc33151625b2e06ea216828247cb24507_s1_n2.png\" alt=\"\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <p class=\"cell\">\r\n");
      out.write("        (서울특별시 중구 남대문로 120 그레이츠 청계(구 대일빌딩) 2F, 3F (T: 1544-9970 / F: 02-722-0858) <br>\r\n");
      out.write("        대표이사 : 배주영 ｜사업자등록번호 :  ｜ 통신판매업신고번호 : 2017-서울용산-0662 <br>\r\n");
      out.write("        호스팅사업자 : CJ올리브네트웍스｜개인정보보호 책임자 : 강병준｜대표이메일 : cjcgvmaster@cj.net｜CGV고객센터 : 010-xxxx-xxxx<br>\r\n");
      out.write("        © CJ CGV. All Rights Reserved\r\n");
      out.write("    </p>\r\n");
      out.write("    <div class=\"cc cell-right\">\r\n");
      out.write("        <a href=\"#\">극장찾기</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"cd cell-right\">\r\n");
      out.write("        <a href=\"#\"><img src=\"https://img.megabox.co.kr/static/pc/images/common/ico/ico-twitter.png\" alt=\"\"></a>\r\n");
      out.write("        <a href=\"#\"><img src=\"https://img.megabox.co.kr/static/pc/images/common/ico/ico-facebook.png\" alt=\"\"></a>\r\n");
      out.write("        <a href=\"#\"><img src=\"https://img.megabox.co.kr/static/pc/images/common/ico/ico-instagram.png\" alt=\"\"></a>\r\n");
      out.write("        <a href=\"#\"><img src=\"https://img.megabox.co.kr/static/pc/images/common/ico/ico-googleplay.png\" alt=\"\"></a>\r\n");
      out.write("        <a href=\"#\"><img src=\"https://img.megabox.co.kr/static/pc/images/common/ico/ico-appstore.png\" alt=\"\"></a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"qqq\"></div>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
